generator/vulkan/build-integration.zig

On windows because we fail to close the output_file, when the compiler 
goes to open it when reading the file during compiling the actual app it
encounters a sharing violation. This change closes the file, fixing that issue

Solve a sharing violation on windows

---

README.md
generator/vulkan/parse.zig

Before discovering this repository i was working on my own vulkan bindings generator and also noticed that pNext was not marked as optional. I got a pull request through in the Vulkan-Docs repo so now it's correctly marked as optional. 
This PR depends on #4 for the triangle example to work.

Removed special case for member pNext.

---

README.md
examples/graphics_context.zig
generator/vulkan/render.zig

Following the discussion in the Zig Discord, I implemented what I believe is a less verbose and more usable interface. 
This makes using the library much less boilerplate-y, and now information is communicated to it via function calls, not field declarations, which I think makes more sense. 
Let me know how you think this compares to the status quo.

Less verbose interface via `@Type`

---

zig.mod

Note: requires <https://github.com/nektro/zigmod/releases/tag/v48> or later.
With this change, users can incorporate into their `build.zig` via the following:
```zig
const deps = @import("./deps.zig");
const vkgen = deps.imports.vulkan_zig;
// ... using `vkgen` as normal
```

add native support for Zigmod package manager

---

generator/vulkan/parse.zig
generator/vulkan/registry.zig
generator/vulkan/render.zig

In Zig, unlike C, you have to initialize everything explicitly. 
This is generally good, but sometimes in Vulkan you are expected to make use of the C/C++ ability to zero-initialize unmentioned fields, particularly in feature structs.
For example, currently you have to do this if you're using `vulkan-zig`:
```zig
const device_features = vk.PhysicalDeviceVulkan12Features {
.buffer_device_address = vk.TRUE,
.sampler_mirror_clamp_to_edge = vk.FALSE,
.draw_indirect_count = vk.FALSE,
.storage_buffer_8_bit_access = vk.FALSE,
.uniform_and_storage_buffer_8_bit_access = vk.FALSE,
.storage_push_constant_8 = vk.FALSE,
.shader_buffer_int_64_atomics = vk.FALSE,
.shader_shared_int_64_atomics = vk.FALSE,
.shader_float_16 = vk.FALSE,
.shader_int_8 = vk.FALSE,
.descriptor_indexing = vk.FALSE, …
```

Implements default for feature structs

---

generator/vulkan/render.zig

As per discussion at the end of #15, this adds defaults for an additional feature struct that my last PR didn't detect.

Adds defaults for previously undetected feature struct

---

examples/triangle.zig

I am porting this example to [mach-glfw](github.com/hexops/mach-glfw), and noticed that no GLFW error handling callback is registered because in my port there are a lot of GLFW errors :)
`glfwSwapBuffers` here is emitting `GLFW_NO_WINDOW_CONTEXT` errors constantly, because calling it without a valid OpenGL context is illegal. It's not needed for Vulkan.

examples: do not call glfwSwapBuffers

---

examples/graphics_context.zig
generator/vulkan/render.zig

Pros:
* Slightly better error message when passing in a non-existent enum value (points at caller's argument instead of the point in the function where the enum literal fails to coerce).
* Clearer function signature.
* Removes the possibility of, eg. `BaseWrapper([_]BaseCommand{ .createInstance })` not being equal to `BaseWrapper(.{ .createInstance })`, thanks to coercion happening at the callsite, and erego evading possible code bloat in niche circumstances.
Cons:
* Breaking, since `.{ ... }` doesn't coerce to being a slice; though, this would be a quick fix, by just prefixing it with '&', a la `&.{ ... }`.
* (Am I missing anything?)
Context:
I was trying to make some functions generic over possible `InstanceWrapper` productions, and ran into an issue where, in a type-checking function …

Replace `anytype` with explicit `[]const {s}Command`

---

README.md

The Vulkan XML registry changed their name from "master" to "main". This bit me when I followed the link in the README, didn't read too carefully that it was X commits behind, and downloaded a pretty old and incompatible version of `vk.xml` by mistake.

Updated Vulkan XML registry master branch name

---

generator/xml.zig

`std.mem.dupe` was recently hard deprecated:
```zig
ziglang/zig/build/lib/zig/std/mem.zig:908:18: error: deprecated; use `Allocator.dupe`
pub const dupe = @compileError("deprecated; use `Allocator.dupe`");
^
./generator/xml.zig:604:19: note: referenced here
return try mem.dupe(alloc, u8, ctx.source[begin..end]);
^
./generator/xml.zig:590:12: note: referenced here
while (try tryParseComment(ctx, alloc)) |_| {
^
./generator/xml.zig:331:5: note: referenced here
try trySkipComments(ctx, &doc.arena.allocator);
^
./generator/xml.zig:319:12: note: referenced here
return try parseDocument(&ctx, backing_allocator);
^
./generator/vulkan/generator.zig:178:18: note: referenced here
const spec = try xml.parse(allocator, spec_xml);
^
./generator/vulkan/build_integration.zig:78:9: note: referenced here …
```

use Allocator.dupe instead of std.mem.dupe

---

generator/main.zig

The generator no longer compiles because of changes to the return type of ArgIterator.next(). ArgIterator.next() returns an optional error union type, the potential error has to be handled before the optional can be unwrapped.

Fix order of handling of optional error union type in generator

---

generator/build_integration.zig

Current setup works fine if passed static memory like '&.{ "glslc" }', but produces errors of various types (segmentation faults, access denied, file doesn't exist, etc) if passed a runtime-known slice, such as a slice containing the result of a call to `Builder.pathJoin`, a la `const glslc_cmd = b.pathJoin(&.{ b.env_map.get("VULKAN_SDK").?, "bin", "glslc" })`, which could then be naively passed as `&.{ glslc_cmd }`. This change prevents issues with temporary runtime argument values.

Copy array of strings instead of assuming lifetime

---

build.zig
generator/build_integration.zig

I made these on my own fork, figured they were general enough that you might be interested as well:
1. Generate shader files with `.spv` appended to the filename - the status quo where there were files generated that ended in `.frag`/`.vert`/`.glsl` but weren't actually human-readable GLSL files bothered me.
2. Allow the user to specify the directory within `zig-cache/` that shaders are placed into. Just needed this for my own project.

Tweaks to shader build integration

---

examples/graphics_context.zig

When using more than one device extension. It will trigger segfault at this function call
https://github.com/Snektron/vulkan-zig/blob/e37b7a0f1b7293c158119b66092a64961bf7a75f/examples/graphics_context.zig#L213-L222

fix segfault when add more device extensions in example

---

build.zig
generator/vulkan/build_integration.zig

``Pkg.path`` was renamed to ``Pkg.source`` in commit https://github.com/ziglang/zig/commit/4e918873e7667e8d74b009cb34cbdd4df3305462

update to latest zig

---

build.zig
generator/build_integration.zig
generator/index.zig

Hello! I have added some functionality to support multiple entrypoints, as I have some HLSL shaders that have two entrypoints I'd like to use without changing. I've tried to make the interface change relatively small, but it does change it in that calls to `add` need to pass an empty param object.
An alternative which would avoid the interface change would be to add a second function `addWithOptions` or something like that. Please LMK if you prefer that.

Add support for multiple entrypoints, specifying stage, and a custom output file for shader compilation

---

examples/graphics_context.zig
examples/swapchain.zig
examples/triangle.zig
generator/vulkan/c_parse.zig
generator/vulkan/parse.zig
generator/vulkan/registry.zig
generator/vulkan/render.zig

Given that using just the C Vulkan headers in C one can default-initialize a lot of Vulkan struct fields via struct initializers, it makes sense to follow that behavior in Zig as well.

More defaults for struct fields

---

.github/workflows/build.yml
README.md
build.zig
generator/build_integration.zig
generator/vulkan/build_integration.zig

First commit updates build.zig and the build_integration.zig files to use the latest build system changes, and makes `GenerateStep` use the new caching API.
The second commit "lightly" modifies build.zig to accommodate the zig package manager, enough to generate the vulkan bindings, though not enough to take advantage of the shader compilation steps.

build system updates

---

generator/build_integration.zig

This PR fixes a bug in the calculation of the output path of the shaders, the cache root and build root where concataneted together resulting in nested full paths. If your where building vulkan zig at ```/home/name/vulkan-zig``` then the shader path would be ```/home/name/vulkan-zig/home/name/vulkan-zig/zig-cache/shaders```.

Fixed bug in shader output path

---

examples/graphics_context.zig
examples/triangle.zig
generator/vulkan/c_parse.zig
generator/vulkan/generator.zig
generator/vulkan/render.zig

Fixed code where ```0..``` needed to be added and improved code with the use of the multi for syntax where possible.

Fixed code to conform to new multi-for syntax

---

build.zig
generator/index.zig

This PR exports ```ShaderCompileStep``` and ```VkGenerateStep``` in order to allow packages using vulkan-zig to import and use these steps in their own build.zig.
```ShaderStage``` is also removed from ```generator/index.zig``` because it no longer exists.

Export ShaderCompileStep and VkGenerateStep

---

README.md
build.zig
generator/build_integration.zig
generator/vulkan/build_integration.zig

- Step now holds the builder and some manifest/cache helpers
- cleaned up proxy names and remaining uses of `std.build`
- removed vicious lie from README
- the run condition was unnecessary (it was a bug workaround), and now also broken

Update for zig build changes

---

build.zig

After attempting to build with the master branch of zig, there was an error indicating that `exe.install()` is deprecated.

Fixed deprecated install step

---

generator/build_integration.zig
generator/vulkan/build_integration.zig

I'm not sure this is a desired patch, but I made this commit so that I can actually connect hashes to the original shader names. 
I use this to copy the shaders to an assets folder that the program is aware of with their original names. This is desired in my project because a shader can then be swapped by end users (not that there are any :D)
The downside is of course some substantial bloat per Shader

Expose shader hash

---

README.md

vulkan-zig accepts only 2 parameters now

Fix outdated README "generation from build.zig" instructions

---

examples/graphics_context.zig

Am honestly not sure if this is objectively better, but I can imagine that it's cleaner to rely on GLFW proc only to load the vkb. then rely on the vkb for everything else after that. Feedback is appreciated!

load the instance proc addr from vkb instead of the loader

---

README.md

The README linked the vulkan-tutorial with the wrong tld.

fix-readme-links

---

generator/vulkan/c_parse.zig
generator/vulkan/parse.zig
generator/vulkan/registry.zig

For procedure parameters which are of pointer type: if the associated `count` parameter is marked `optional` in the XML, this commit makes the parameter pointer type nullable.
Effectively, parameters of type `[*]` are now `?[*]` if the spec allows their associated `count` parameter to be 0.
This had already been implemented for struct members. This code is pretty much the same.
Resolves #40.

Nullable pointer parameters

---

generator/vulkan/parse.zig

Resolves #100.
This is the entire difference in the generated Zig code:
```diff
@@ -1107,11 +1107,11 @@
pub const PipelineLayoutCreateInfo = extern struct {
s_type: StructureType = .pipeline_layout_create_info,
p_next: ?*const anyopaque = null,
flags: PipelineLayoutCreateFlags = .{},
set_layout_count: u32 = 0,
-    p_set_layouts: [*]const DescriptorSetLayout,
+    p_set_layouts: ?[*]const DescriptorSetLayout = null,
push_constant_range_count: u32 = 0,
p_push_constant_ranges: ?[*]const PushConstantRange = null,
};
@@ -3281,11 +3281,11 @@
pub const DescriptorSetLayoutBindingFlagsCreateInfo = extern struct {
s_type: StructureType = .descriptor_set_layout_binding_flags_create_info,
p_next: ?*const anyopaque = null,
binding_count: u32 = 0,
-    p_binding_flags: [*]const DescriptorBindingFlags, …
```

Fix `optional` detection conflict

---

generator/vulkan/build_integration.zig

Hi,
As stated by this pull request title, it just provides some logs when `std.zig.Ast.parse()` failed to avoid some potential headaches.
Here a demo of the output:
```zig
cons std = @import ("std");
const fmt = std.fmt;
const allocPrint = fmt.allocPrint
fn main () void
{
var i: u32 = 0;
i++;
const j: v32 = undefined,
_ = j;
}
ERROR: zig.Ast.Error{ .tag = zig.Ast.Error.Tag.expected_comma_after_field, .is_note = false, .token_is_prev = false, .token = 1, .extra = zig.Ast.Error.Error__union_6445@7ffe2d1231c0 }
TOKEN: zig.tokenizer.Token{ .tag = zig.tokenizer.Token.Tag.identifier, .loc = zig.tokenizer.Token.Loc{ .start = 0, .end = 4 } }
cons std = @import ("std");
^^^^
ERROR: zig.Ast.Error{ .tag = zig.Ast.Error.Tag.expected_semi_after_decl, .is_note = false, .token_is_prev = true, .token = …
```

Add logs for std.zig.Ast.parse() failure

---

generator/vulkan/render.zig

This changes to format output from:
MyFlagType{ .first_bit = true, second_bit = false, _reserved_bit_0 = false, _reserved_bit_1 = false }
to the following:
MyFlagType{ .first_bit }
That is, we only show bits which are `true`, which reduces noise when logging values.

Format flags

---

README.md

The example was a bit outdated:
* Used the "package" terminology which has been replaced by "module"
* The import didn't work for me
* Missing parameter from ShaderCompileStep.create()
Side note: I don't really understand the purpose of the output flag parameter. What else can it be other than "-o"?
Side note 2: I'm new to Zig, and for some reason the alignment stuff doesn't work for me. I have to use the compiled shaders with `@ptrCast(@alignCast(&my_shader))`; the `@as([*]const u32, @ptrCast(&my_shader))` approach doesn't work. If I knew the right way to do this, I would have included it in the example snippet.

Update "Shader compilation" in README

---

.gitignore
build.zig
generator/build_integration.zig
generator/vulkan/build_integration.zig

there are some formatting changes in there, sorry

fixing up vulkan-zig for new build sys

---

generator/vulkan/render.zig

There seem to have been some leftover old style casts in ```generator/vulkan/render.zig``` which got rendered into vk.zig. I don't know why the library seems to have been working fine up until updating the compiler now.

Fix old style casts in generated vk.zig

---

examples/triangle.zig

Fixes a crash when minimizing the window in the triangle example due to the window size becoming zero as well as two minor changes. Also changes the swapchain to use the GLFW framebuffer size instead of the window size as iirc they can differ and the swapchain expects the framebuffer size since both operate in pixels.
Edit: Added a `deviceWaitIdle` call before the program exits since I got Vulkan validation errors about semaphores being deleted while still in use with the validation layer enabled.

[Triangle Example] Fix crash when minimizing window

---

generator/vulkan/build_integration.zig

Build `Cache` was moved from `std.Build` to `std.Build.Graph`.

Compile on Zig master

---

generator/main.zig

The `InvalidCmdLine` error got removed from `argsWithAllocator` error set on master

remove no longer used error from set

---

generator/vulkan/render.zig

reflect changes made in https://github.com/ziglang/zig/commit/8af59d1f98266bd70b3afb44d196bbd151cedf22

fix: change ComptimeStringMap to StaticStringMap

---

build.zig
examples/graphics_context.zig
generator/vulkan/render.zig

This fixes #112, 
As I note on line 1067, some extensions (`VK_KHR_push_descriptor` and `VK_EXT_full_screen_exclusive`) end up defining the same function twice. The duplicates are simply removed for now, but I am curious if it would be worth exposing the functions within each require separately rather than all at once. It is entirely possible I am misunderstanding the cause of the duplicate functions.
Feel free to commit directly to my fork, and let me know of any issues.

Add extension function metadata for #112

---

examples/graphics_context.zig
src/vulkan/render.zig

This unifies command info even more, by making the user first construct a list of `ApiInfo` to represent the api that they want to use. This allows for much easier composition of different extensions and features.
Implements #112

unified command info ii

---

README.md
src/vulkan/render.zig

This change is what is needed to make Mach engine / sysgpu happy
Fixes Snektron/vulkan-zig#125

always provide default opaque{} external type implementations

---

src/build_integration.zig

I am not sure, if the output of the child process should be used or not, but this change lets it compile again.

update to 0.14.0-dev.91+a154d8da8

---

examples/graphics_context.zig
examples/swapchain.zig
src/vulkan/render.zig

Closes #145
Could probably still use a little cleanup, but I think it's getting there. Some places could be improved using string interpolation instead of calling the `render*()` functions, but the problem is they have some handling of casing, prefix stripping, etc. that would need to be duplicated or refactored in order to get the formatted names as a string. Shouldn't be too bad but not sure whether it's worth cluttering up the existing code for this, let me know if you want me to try it that way.
TODO:
- ~fill in full list of functions~
- ~add proxy functions~
- ~update examples~
Output (mostly unchanged from the issue):
```zig
pub const EnumerateInstanceExtensionPropertiesAllocError =
EnumerateInstanceExtensionPropertiesError || Allocator.Error;
pub fn …
```

Array function wrappers

---

examples/build.zig
src/build_integration.zig

This allows for passing paths to executables generated by the compiler as the compile command.

Add ability to pass a LazyPath as compile command to the ShaderCompileStep

---

src/vulkan/render.zig

The limit is being hit when enabling core APIs up to 1.3, reproducible with the triangle example:
```
diff --git a/examples/graphics_context.zig b/examples/graphics_context.zig
index f2d0fef..452de08 100644
--- a/examples/graphics_context.zig
+++ b/examples/graphics_context.zig
@@ -18,6 +18,9 @@ const apis: []const vk.ApiInfo = &.{
},
// Or you can add entire feature sets or extensions
vk.features.version_1_0,
+    vk.features.version_1_1,
+    vk.features.version_1_2,
+    vk.features.version_1_3,
vk.extensions.khr_surface,
vk.extensions.khr_swapchain,
};
```
```
$ zig build
install
└─ install triangle
└─ zig build-exe triangle Debug native 1 errors
/home/poconn/.local/bin/lib/std/meta.zig:553:12: error: evaluation exceeded 100000 backwards branches
inline for (field_infos, 0..) |field, …
```

Increase eval branch quota

---

README.md

Fixed errors in the example code that shows how to use the vulkan_headers dependency to generate the bindings.
The errors were:
`generate_cmd.addArg(registry);`: `generate_cmd` variable does not exist, it should be `vk_generate_cmd`
`vk_generate_cmd.addArg(registry);`: `addArg()` takes a `[]const u8` and was given a `LazyPath`, used `addFileArg()` instead

docs: Fixed compilation error in README.md example

---

src/vulkan/render.zig

This PR makes it possible to have dispatch structs that do not include unneeded function pointers.
See #177

Allow custom Dispatch structs

---

src/vulkan/render.zig

[`std.builtin.Type.StructField.name`](https://ziglang.org/documentation/master/std/#std.builtin.Type.StructField) has type `[:0]const u8`.
LLVM-IR before this PR:
```llvm
@__anon_13958 = internal unnamed_addr constant [18 x i8] c"vkCreateInstance\00\00", align 1
@__anon_13974 = internal unnamed_addr constant [23 x i8] c"vkGetInstanceProcAddr\00\00", align 1
@__anon_13985 = internal unnamed_addr constant [28 x i8] c"vkEnumerateInstanceVersion\00\00", align 1
@__anon_13996 = internal unnamed_addr constant [36 x i8] c"vkEnumerateInstanceLayerProperties\00\00", align 1
@__anon_14010 = internal unnamed_addr constant [40 x i8] c"vkEnumerateInstanceExtensionProperties\00\00", align 1
```
After this PR:
```llvm
@__anon_13896 = internal unnamed_addr constant [17 x i8] c"vkCreateInstance\00", align …
```

Remove additional null termination

---

examples/swapchain.zig

When resizing the window created by the example the `acquireNextImageKHR` call may return `.suboptimal_khr`. This will then crash the example with a segmentation fault since some resources are de-initialized twice, such as the swapchain handle and swapchain images.

Fix crash of the example related to swapchain recreation during resizing.

---

examples/triangle.zig

When running the example on a Wayland system using a scaling factor of 3, the example crashes since the size of the initial buffer created by GLFW is not divisible by the scaling factor. This violates the Wayland protocol, which results in a crash when trying to present to the `wl_surface`:
```
wl_surface#24: error 2: Buffer size (554x646) is not divisible by scale (3)
```
Allowing for a resize of the swapchain images before presenting fixes this issue.
I am admittedly not entirely sure why this fixes the issue, since when logging the resizes, there is at least one resize to a buffer size that is invalid, without causing a crash:
```
info: framebuffer size : swapchain extent before resize
info: 554, 646 : 800, 600
info: 1662, 1938 : 554, 646
```
But I assume that this is related to when …

Fixed crash under Wayland when using a scaling factor.
