- generator/vulkan/render.zig
Lays the groundwork for #47.
cc @ashpil
> Replace command enums with command flag structs

- generator/vulkan/render.zig
Change was made to Zig: https://github.com/ziglang/zig/pull/13101/files
So needs to be changed here too.
> updated platform enumeration for 0.11.0

- generator/vulkan/render.zig
- test/ref_all_decls.zig
breaking zig commit: https://github.com/ziglang/zig/pull/13930/commits/aac2d6b56f32134ea32fb3d984e3fcdfddd8aaf6
> rename StructField field_type to type

- generator/build_integration.zig
Closes #61
First Zig PR hype!!
> Copy src path in ShaderCompileStep.add

- build.zig
addShaderBase64 allows for the inclusion of spv binaries without using @embedfile, since @embedfile has certain restrictions on file locations.
> Added option to add shaders as base64 instead of embedding file

- build.zig
- generator/build_integration.zig
This also removes some glslc-specific nice-to-haves, but I'm not sure if there's a way around that.
> Remove a couple glslc specific assumptions to allow an arbitrary shader compiler

- generator/build_integration.zig
> Allow specifying additional watches files for shader compilation caching

- build.zig
- generator/main.zig
- generator/vulkan/build_integration.zig
Updating build script to latest  build system changes and also Zig AST parse
> Update to build system changes

- README.md
- build.zig
- generator/build_integration.zig
- generator/vulkan/build_integration.zig
Use the new module API 
Resolve issue #75
> update build to use new build API

- build.zig
The new module API now returns the created module as well as taking some different parameters.
> Use new module API

- generator/vulkan/render.zig
This resolves compile error with master zig
> explicitly cast boolToInt in Wrapper

- examples/graphics_context.zig
Am no expert at Zig but this seems to work, any feedback is appreciated.
> use std.mem.sliceTo instead of indexOfScalar

- README.md
The byte slice required to be constant and it was giving a compile error.
> Fix README compile error.

- examples/triangle.zig
Updates builtins to follow new xFromY style instead of xToY.
> Update intToFloat builtin to floatFromInt

- generator/main.zig
try cannot work since main's return type does not accept errors anymore
> Fix compile error for the generator

- generator/vulkan/render.zig
sync changes with zig master branch
099f3c4039d5702b073639ef8b55881973b71c80.
> make ContainerLayout field lowercase

- generator/build_integration.zig
- generator/vulkan/build_integration.zig
Fix breakage introduced by https://github.com/ziglang/zig/pull/19470
> Fix broken @fieldParentPtr

- .github/workflows/build.yml
> ci: format check

- build.zig.zon
- examples/build.zig.zon
now compiles with latest zig (aka `0.14`)
> build: add fingerprint

- README.md
- examples/graphics_context.zig
- src/vulkan/render.zig
This makes the library easier to use, and the expense of maybe some hypothetical function pointer cache misses. I think its worth it, but some user feedback would be nice.
> remove wrapper/proxy configurability, just load everything unconditionally

- examples/graphics_context.zig
closes issue #137 
I'm very new to zig and low level programming so any feedback is appreciated.
> changes to support 1.3.216 Vulkan SDK and above

- examples/triangle.zig
The requested dimensions of a newly created window may be different from the actual dimensions as the window system may enforce additional restrictions. This happens, for example, when using Wayland with a scaling factor of 3 (the default width of 800 is not divisible by 3).
To fix it, just re-query the actual framebuffer size after creating the window. The GLFW documentation also suggests to do this:
> The created window, framebuffer and context may differ from what you requested,
> as not all parameters and hints are hard constraints. This includes the size of
> the window, especially for full screen windows. To query the actual attributes
> of the created window, framebuffer and context, see glfwGetWindowAttrib,
> glfwGetWindowSize and glfwGetFramebufferSize.
-- …
> fix window extent after creating

- src/vulkan/render.zig
> Format function signature

- examples/graphics_context.zig
I've found this graphics context as a useful starting place for a few projects now. I think it'd be great to have validation messages in there and other people might find it useful too.
P.S. Thanks for making and maintaining this library, it's great!
> Debug messages
